name = "TypeTree"
uuid = "04da0e3b-1cad-4b2c-a963-fc1602baf1af"
authors = ["C Naaktgeboren <NaaktgeborenC.PhD@gmail.com>"]
version = "0.3.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[compat]
julia = "^1.6"
